version: '2'

services:
    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
          es_net:
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
        networks:
          es_net:
    php:
        build: docker/php7.0-fpm
        ports:
            - 9000:9000
        links:
            - db:mysqldb
            - redis
            - elasticsearch
        volumes:
            - ./:/var/www/miniwaveme
            - ./logs/miniwaveme:/var/www/miniwaveme/app/logs
        depends_on:
            - elasticsearch
        networks:
          es_net:

    nginx:
        build: docker/nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
        networks:
          es_net:

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
        networks:
          es_net:
            aliases:
              - elasticsearch
        mem_limit: 1g
        environment:
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          - "discovery.zen.ping.unicast.hosts=elasticsearch"
          - "xpack.security.enabled=false"
        volumes:
          - "./.data/elasticsearch:/usr/share/elasticsearch/data"
        ports:
          - 9200:9200

networks:
  es_net:
    driver: bridge