imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

snc_redis:
    doctrine:
        metadata_cache:
            client: doctrine_predis_cache
            entity_manager: default
            namespace: "%kernel.root_dir%"
        result_cache:
            client: doctrine_predis_cache
            entity_manager: default
            namespace: "%kernel.root_dir%"
        query_cache:
            client: doctrine_predis_cache
            entity_manager: default
            namespace: "%kernel.root_dir%"
