imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: forms.yml }
    - { resource: repositories.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_oauth_server:
    db_driver: orm
    client_class:        AppBundle\Entity\OAuth\Client
    access_token_class:  AppBundle\Entity\OAuth\AccessToken
    refresh_token_class: AppBundle\Entity\OAuth\RefreshToken
    auth_code_class:     AppBundle\Entity\OAuth\AuthCode

    service:
        user_provider: app.user_provider

fos_rest:
    param_fetcher_listener: true

    view:
        view_response_listener: true
        formats:
            json: true
            html: true

    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
        decoders:
            json: fos_rest.decoder.json

    body_converter:
        enabled: true
        validate: true

    allowed_methods_listener: true

    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true }
            - { path: '^/_', stop: true }

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://%redis_host%

        predis_cache:
            type: predis
            alias: predis_cache
            dsn: redis://%redis_host%/1

        doctrine_predis_cache:
            type: predis
            alias: doctrine_predis_cache
            dsn: redis://%redis_host%/2

    doctrine:
        metadata_cache:
            client: doctrine_predis_cache
            entity_manager: default
            namespace: "%kernel.root_dir%"
        result_cache:
            client: doctrine_predis_cache
            entity_manager: default
            namespace: "%kernel.root_dir%"
        query_cache:
            client: doctrine_predis_cache
            entity_manager: default
            namespace: "%kernel.root_dir%"

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true

doctrine_cache:
    aliases:
        app.cache.predis: predis_cache

    providers:
        predis_cache:
            predis:
                client_id: snc_redis.predis_cache
vich_uploader:
    db_driver: orm
    mappings:
        album_art_image:
            uri_prefix:         /images/album-art
            upload_destination: '%kernel.root_dir%/../web/images/album-arts'
            delete_on_remove:   true

        artist_image:
            uri_prefix:         /images/artist
            upload_destination: '%kernel.root_dir%/../web/images/artists'
            delete_on_remove:   true

        audio_file:
            uri_prefix:         /files/audio
            upload_destination: '%kernel.root_dir%/../web/files/audio'
            delete_on_remove:   true

liip_imagine:
    filter_sets:
        cover_thumb:
            cache: cached_predis_covers
            quality: 75
            filters:
                thumbnail: { size: [120, 120], mode: outbound }

        cover_medium:
            cache: cached_predis_covers
            quality: 80
            filters:
                thumbnail: { size: [360, 360], mode: outbound }
        cover_hight:
            cache: cached_predis_covers
            quality: 85
            filters:
                thumbnail: { size: [480, 480], mode: outbound }

        artist_thumb:
            cache: cached_predis_artists
            quality: 75
            filters:
                thumbnail: { size: [120, 120], mode: outbound }

        artist_medium:
            cache: cached_predis_artists
            quality: 80
            filters:
                thumbnail: { size: [360, 360], mode: outbound }
        artist_hight:
            cache: cached_predis_artists
            quality: 85
            filters:
                thumbnail: { size: [480, 480], mode: outbound }