services:
  app.repository.album:
    class: AppBundle\Repository\ORM\AlbumRepository
    factory: "doctrine:getRepository"
    arguments: [Socloz\AppBundle\Entity\Album]

  app.repository.artist:
    class: AppBundle\Repository\ORM\ArtistRepository
    factory: "doctrine::getRepository"
    arguments: [Socloz\AppBundle\Entity\Artist]

  app.repository.track:
    class: AppBundle\Repository\ORM\TrackRepository
    factory: "doctrine::getRepository"
    arguments: [Socloz\AppBundle\Entity\Track]

  app.repository.user:
    class: AppBundle\Repository\ORM\UserRepository
    factory: "doctrine::getRepository"
    arguments: [Socloz\AppBundle\Entity\User]
