parameters:
    imagine.album_arts.web_root: "%kernel.root_dir%/../web"
    imagine.album_arts.cache_prefix: "images/album_arts/cache"

    imagine.artists.web_root: "%kernel.root_dir%/../web"
    imagine.artists.cache_prefix: "images/artists/cache"

services:
    app.user_provider:
        class: AppBundle\Security\User\UserProvider
        arguments:
          - "@app.repository.user"

    app.service.user:
        class: AppBundle\Service\UserService
        arguments:
            - "@app.repository.user"

    app.imagine.cache.album_arts.resolver.web_path:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\WebPathResolver
        arguments:
            - "@filesystem"
            - "@router.request_context"
            - "%imagine.album_arts.web_root%"
            - "%imagine.album_arts.cache_prefix%"

    app.imagine.cache.artists.resolver.web_path:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\WebPathResolver
        arguments:
            - "@filesystem"
            - "@router.request_context"
            - "%imagine.artists.web_root%"
            - "%imagine.artists.cache_prefix%"

    app.imagine.cache.album_arts.resolver.web_path.cache:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\CacheResolver
        arguments:
            - "@app.cache.predis"
            - "@app.imagine.cache.album_arts.resolver.web_path"
            - { prefix: "predis" }
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: "cached_predis_album_arts" }

    app.imagine.cache.artists.resolver.web_path.cache:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\CacheResolver
        arguments:
            - "@app.cache.predis"
            - "@app.imagine.cache.artists.resolver.web_path"
            - { prefix: "predis" }
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: "cached_predis_artists" }
