# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.user_provider:
        class: AppBundle\Security\User\UserProvider
        arguments:
          - "@app.repository.user"

    app.service.user:
        class: AppBundle\Service\UserService
        arguments:
            - "@app.repository.user"

    app.imagine.cache.covers.resolver.web_path:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\WebPathResolver
        arguments:
            - "@filesystem"
            - "@router.request_context"
            - "%imagine.covers.web_root%"
            - "%imagine.covers.cache_prefix%"

    app.imagine.cache.artists.resolver.web_path:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\WebPathResolver
        arguments:
            - "@filesystem"
            - "@router.request_context"
            - "%imagine.artists.web_root%"
            - "%imagine.artists.cache_prefix%"

    app.imagine.cache.covers.resolver.web_path.cache:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\CacheResolver
        arguments:
            - "@cache.predis"
            - "@app.imagine.cache.covers.resolver.web_path"
            - { prefix: "predis" }
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: "cached_predis_covers" }

    app.imagine.cache.artists.resolver.web_path.cache:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\CacheResolver
        arguments:
            - "@cache.predis"
            - "@app.imagine.cache.artists.resolver.web_path"
            - { prefix: "predis" }
        tags:
            - { name: "liip_imagine.cache.resolver", resolver: "cached_predis_artists" }

    cache.predis:
        class: Doctrine\Common\Cache\PredisCache
        arguments:
            - "@snc_redis.default"
